### ISSUE TITLE
Issue1

### ISSUE THREAD

**Issue by fumiaki1108** [fumiaki1108/furima--31651-#1]
DB設計

**Comment by fumiaki1108** [comment]
https://gyazo.com/a5cc9d2abb57189363333d4defed8efd

**Comment by fumiaki1108** [comment]
誤ってマージしてしまったのですが、こちらで確認していただいても大丈夫ですか？
https://github.com/fumiaki1108/furima-31651/commit/b4508180313334f9fbec6b64a185e4824c26564b

**Comment by ghost** [comment]
レビュー依頼ありがとうございます。

以下の点の修正をお願いいたします。

---

**Emailに一意性制約を設けましょう。**

**理由**
要件に「メールアドレスが一意性であること」とあるためです。

---

修正後は、マージを一旦取り消して再度プルリクエストの作成をお願いいたします。
マージ取り消しの手順につきまして、不明な場合はテックコネクトで通話質問頂けますでしょうか。

お手数をお掛けしますが、何卒よろしくお願いいたします。
